import { useMemo, useState } from "react";
import type {
  N8nAudioResponse,
  N8nFlashcardsResponse,
  N8nMindMapResponse,
  N8nQuizResponse,
  N8nSlidesResponse,
  N8nTablesResponse,
  QuizQuestion,
} from "../../lib/n8n";
import type { AIToolName } from "../dashboard/dashboardTypes";

type AIToolResultRendererProps = {
  toolName: AIToolName;
  result: unknown;
};

type TableColumn = {
  key: string;
  label: string;
};

type TableRow = Record<string, unknown>;

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === "object" && value !== null;
};

const isQuizResponse = (result: unknown): result is N8nQuizResponse => {
  return isRecord(result) && isRecord(result.quiz);
};

const isFlashcardsResponse = (
  result: unknown,
): result is N8nFlashcardsResponse => {
  return (
    isRecord(result) &&
    isRecord(result.deck) &&
    Array.isArray(result.deck.cards)
  );
};

const isTablesResponse = (result: unknown): result is N8nTablesResponse => {
  return (
    isRecord(result) &&
    isRecord(result.table) &&
    Array.isArray(result.table.rows)
  );
};

const isMindMapResponse = (result: unknown): result is N8nMindMapResponse => {
  return isRecord(result) && isRecord(result.mindMap);
};

const isSlidesResponse = (result: unknown): result is N8nSlidesResponse => {
  return (
    isRecord(result) &&
    isRecord(result.deck) &&
    Array.isArray(result.deck.slides)
  );
};

const isAudioResponse = (result: unknown): result is N8nAudioResponse => {
  return isRecord(result) && isRecord(result.audioOverview);
};

const normalizeAnswer = (value: string) => value.trim().toLowerCase();

const shuffleArray = <T,>(items: T[]) => {
  return [...items].sort(() => Math.random() - 0.5);
};

const formatProviderName = (provider: string) => {
  return provider
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

const getProviderLabel = (result: unknown) => {
  if (!isRecord(result)) return "";

  const provider = typeof result.provider === "string" ? result.provider : "";
  const fallback = result.fallback === true;

  if (!provider && fallback) return "Fallback output";
  if (!provider) return "";

  return fallback
    ? `Generated by ${formatProviderName(provider)} fallback`
    : `Generated by ${formatProviderName(provider)}`;
};

const ProviderBadge = ({ result }: { result: unknown }) => {
  const label = getProviderLabel(result);

  if (!label) return null;

  return (
    <span className="inline-flex rounded-full border border-aura-gold/40 bg-aura-gold/10 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-aura-gold">
      {label}
    </span>
  );
};

const FallbackJsonView = ({ result }: { result: unknown }) => {
  return (
    <pre className="aura-scrollbar max-h-[52vh] overflow-auto rounded-2xl border border-aura-border bg-aura-bg px-4 py-4 text-xs leading-6 text-aura-muted">
      {JSON.stringify(result, null, 2)}
    </pre>
  );
};

const getRowValue = (
  row: TableRow,
  column: TableColumn,
  columnIndex: number,
) => {
  const directValue = row[column.key];

  if (directValue !== undefined && directValue !== null && directValue !== "") {
    return String(directValue);
  }

  const labelValue = row[column.label];

  if (labelValue !== undefined && labelValue !== null && labelValue !== "") {
    return String(labelValue);
  }

  const lowerKey = column.key.toLowerCase();
  const lowerLabel = column.label.toLowerCase();

  const matchingEntry = Object.entries(row).find(([key]) => {
    const normalizedKey = key.toLowerCase().replace(/[^a-z0-9]/g, "_");
    const normalizedLabel = lowerLabel.replace(/[^a-z0-9]/g, "_");

    return (
      normalizedKey === lowerKey ||
      normalizedKey === normalizedLabel ||
      key.toLowerCase() === lowerLabel
    );
  });

  if (matchingEntry?.[1] !== undefined && matchingEntry[1] !== null) {
    return String(matchingEntry[1]);
  }

  const fallbackValue = Object.values(row)[columnIndex];

  if (fallbackValue !== undefined && fallbackValue !== null) {
    return String(fallbackValue);
  }

  return "—";
};

const SavedQuizResult = ({ result }: { result: N8nQuizResponse }) => {
  const [questions, setQuestions] = useState<QuizQuestion[]>(
    result.quiz.questions,
  );
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string>>(
    {},
  );
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);

  const currentQuestion = questions[currentQuestionIndex];
  const answeredCount = Object.keys(selectedAnswers).length;

  const score = useMemo(() => {
    return questions.reduce((total, question, index) => {
      const selectedAnswer = selectedAnswers[index];

      if (
        selectedAnswer &&
        normalizeAnswer(selectedAnswer) === normalizeAnswer(question.answer)
      ) {
        return total + 1;
      }

      return total;
    }, 0);
  }, [questions, selectedAnswers]);

  const accuracy = questions.length
    ? Math.round((score / questions.length) * 100)
    : 0;

  const selectedAnswer = selectedAnswers[currentQuestionIndex];

  const isCorrect =
    selectedAnswer &&
    currentQuestion &&
    normalizeAnswer(selectedAnswer) === normalizeAnswer(currentQuestion.answer);

  const progressPercentage = questions.length
    ? Math.round(((currentQuestionIndex + 1) / questions.length) * 100)
    : 0;

  const handleSelectAnswer = (answer: string) => {
    if (isSubmitted) return;

    setSelectedAnswers((currentAnswers) => ({
      ...currentAnswers,
      [currentQuestionIndex]: answer,
    }));
  };

  const handleReset = () => {
    setSelectedAnswers({});
    setIsSubmitted(false);
    setCurrentQuestionIndex(0);
  };

  const handleShuffle = () => {
    setQuestions((currentQuestions) => shuffleArray(currentQuestions));
    setSelectedAnswers({});
    setIsSubmitted(false);
    setCurrentQuestionIndex(0);
  };

  const handlePrevious = () => {
    setCurrentQuestionIndex((current) => Math.max(current - 1, 0));
  };

  const handleNext = () => {
    setCurrentQuestionIndex((current) =>
      Math.min(current + 1, questions.length - 1),
    );
  };

  if (!currentQuestion) {
    return <FallbackJsonView result={result} />;
  }

  return (
    <div className="space-y-4">
      <div className="rounded-[1.5rem] border border-aura-border bg-aura-bg-soft p-5">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.22em] text-aura-cyan">
              Interactive Saved Quiz
            </p>

            <h3 className="mt-1 text-xl font-black text-aura-text">
              {result.quiz.title}
            </h3>

            <p className="mt-2 text-sm leading-6 text-aura-muted">
              Answer one question at a time. Use Previous and Next to navigate.
            </p>

            <div className="mt-3">
              <ProviderBadge result={result} />
            </div>
          </div>

          <div className="grid min-w-full gap-2 sm:grid-cols-2 lg:min-w-[360px]">
            <button
              type="button"
              onClick={handleShuffle}
              disabled={isSubmitted}
              className="rounded-2xl border border-aura-cyan/40 bg-aura-cyan/10 px-4 py-3 text-sm font-black text-aura-cyan transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Randomize
            </button>

            <button
              type="button"
              onClick={handleReset}
              className="rounded-2xl border border-aura-border bg-aura-panel px-4 py-3 text-sm font-black text-aura-muted transition hover:border-aura-cyan/60 hover:text-aura-text"
            >
              Reset
            </button>

            <button
              type="button"
              onClick={() => setIsSubmitted(true)}
              disabled={answeredCount === 0}
              className="rounded-2xl bg-gradient-to-r from-aura-primary via-aura-cyan to-aura-gold px-4 py-3 text-sm font-black text-aura-bg transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 sm:col-span-2"
            >
              Submit Answers
            </button>
          </div>
        </div>

        <div className="mt-5 grid gap-3 sm:grid-cols-3">
          <div className="rounded-2xl border border-aura-border bg-aura-panel p-4">
            <p className="text-2xl font-black text-aura-text">
              {answeredCount}/{questions.length}
            </p>
            <p className="mt-1 text-[10px] font-black uppercase tracking-wider text-aura-dim">
              Answered
            </p>
          </div>

          <div className="rounded-2xl border border-aura-border bg-aura-panel p-4">
            <p className="text-2xl font-black text-aura-text">
              {isSubmitted ? `${score}/${questions.length}` : "--"}
            </p>
            <p className="mt-1 text-[10px] font-black uppercase tracking-wider text-aura-dim">
              Score
            </p>
          </div>

          <div className="rounded-2xl border border-aura-border bg-aura-panel p-4">
            <p className="text-2xl font-black text-aura-text">
              {isSubmitted ? `${accuracy}%` : "--"}
            </p>
            <p className="mt-1 text-[10px] font-black uppercase tracking-wider text-aura-dim">
              Accuracy
            </p>
          </div>
        </div>

        <div className="mt-5">
          <div className="flex items-center justify-between gap-3">
            <p className="text-[10px] font-black uppercase tracking-wider text-aura-dim">
              Question {currentQuestionIndex + 1} of {questions.length}
            </p>

            <p className="text-[10px] font-black uppercase tracking-wider text-aura-cyan">
              {progressPercentage}% Progress
            </p>
          </div>

          <div className="mt-2 h-2 overflow-hidden rounded-full bg-aura-panel">
            <div
              className="h-full rounded-full bg-gradient-to-r from-aura-primary via-aura-cyan to-aura-gold transition-all"
              style={{ width: `${progressPercentage}%` }}
            />
          </div>
        </div>
      </div>

      <div className="rounded-[1.75rem] border border-aura-border bg-aura-bg-soft p-6">
        <div className="flex items-start justify-between gap-3">
          <div>
            <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
              Question {currentQuestionIndex + 1}
            </p>

            <p className="mt-3 text-xl font-black leading-8 text-aura-text">
              {currentQuestion.question}
            </p>
          </div>

          {isSubmitted && (
            <span
              className={`shrink-0 rounded-full border px-3 py-1 text-[10px] font-black uppercase tracking-wider ${
                isCorrect
                  ? "border-emerald-400/40 bg-emerald-500/10 text-emerald-200"
                  : "border-red-400/40 bg-red-500/10 text-red-200"
              }`}
            >
              {isCorrect ? "Correct" : "Review"}
            </span>
          )}
        </div>

        <div className="mt-5 grid gap-3">
          {currentQuestion.choices.map((choice) => {
            const isSelected = selectedAnswer === choice;
            const isCorrectChoice =
              normalizeAnswer(choice) === normalizeAnswer(currentQuestion.answer);

            const submittedClass =
              isSubmitted && isCorrectChoice
                ? "border-emerald-400/60 bg-emerald-500/10 text-emerald-100"
                : isSubmitted && isSelected && !isCorrectChoice
                  ? "border-red-400/60 bg-red-500/10 text-red-100"
                  : "";

            const idleClass = isSelected
              ? "border-aura-cyan/70 bg-aura-cyan/10 text-aura-text"
              : "border-aura-border bg-aura-panel text-aura-muted hover:border-aura-cyan/50 hover:text-aura-text";

            return (
              <button
                key={choice}
                type="button"
                onClick={() => handleSelectAnswer(choice)}
                disabled={isSubmitted}
                className={`rounded-2xl border px-4 py-4 text-left text-sm font-semibold transition ${
                  submittedClass || idleClass
                } disabled:cursor-default`}
              >
                {choice}
              </button>
            );
          })}
        </div>

        {isSubmitted && (
          <div className="mt-5 rounded-2xl border border-aura-border bg-aura-panel p-4">
            <p className="text-sm leading-6 text-aura-muted">
              <span className="font-black text-aura-text">Correct answer:</span>{" "}
              {currentQuestion.answer}
            </p>

            <p className="mt-2 text-sm leading-6 text-aura-muted">
              <span className="font-black text-aura-text">Explanation:</span>{" "}
              {currentQuestion.explanation}
            </p>
          </div>
        )}

        <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <button
            type="button"
            onClick={handlePrevious}
            disabled={currentQuestionIndex === 0}
            className="rounded-2xl border border-aura-border bg-aura-panel px-5 py-3 text-sm font-black text-aura-muted transition hover:border-aura-cyan/60 hover:text-aura-text disabled:cursor-not-allowed disabled:opacity-40"
          >
            ← Previous
          </button>

          <div className="flex flex-wrap justify-center gap-2">
            {questions.map((question, index) => {
              const isActive = index === currentQuestionIndex;
              const isAnswered = selectedAnswers[index];

              return (
                <button
                  key={`${question.question}-${index}`}
                  type="button"
                  onClick={() => setCurrentQuestionIndex(index)}
                  className={`h-3 w-3 rounded-full transition ${
                    isActive
                      ? "bg-aura-cyan"
                      : isAnswered
                        ? "bg-aura-gold"
                        : "bg-aura-border"
                  }`}
                  aria-label={`Go to question ${index + 1}`}
                />
              );
            })}
          </div>

          <button
            type="button"
            onClick={handleNext}
            disabled={currentQuestionIndex === questions.length - 1}
            className="rounded-2xl border border-aura-cyan/40 bg-aura-cyan/10 px-5 py-3 text-sm font-black text-aura-cyan transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Next →
          </button>
        </div>
      </div>
    </div>
  );
};

const AIToolResultRenderer = ({
  toolName,
  result,
}: AIToolResultRendererProps) => {
  if (!result) return null;

  if (toolName === "Quiz" && isQuizResponse(result)) {
    return <SavedQuizResult result={result} />;
  }

  if (toolName === "Cards" && isFlashcardsResponse(result)) {
    return (
      <div className="space-y-4">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.22em] text-aura-cyan">
              Saved Flashcards
            </p>

            <h3 className="mt-1 text-xl font-black text-aura-text">
              {result.deck.title}
            </h3>
          </div>

          <ProviderBadge result={result} />
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          {result.deck.cards.map((card, index) => (
            <details
              key={`${card.prompt}-${index}`}
              className="rounded-2xl border border-aura-border bg-aura-bg-soft p-4"
            >
              <summary className="cursor-pointer list-none">
                <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
                  {card.type === "fill_blank" ? "Fill in the Blank" : "Question"}
                </p>

                <p className="mt-3 text-base font-black leading-7 text-aura-text">
                  {card.prompt}
                </p>

                <p className="mt-3 text-xs font-bold text-aura-dim">
                  Open to reveal answer
                </p>
              </summary>

              <div className="mt-4 rounded-xl border border-aura-cyan/40 bg-aura-cyan/10 p-3">
                <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
                  Answer
                </p>

                <p className="mt-1 text-sm font-bold leading-6 text-aura-text">
                  {card.answer}
                </p>
              </div>

              <p className="mt-3 text-sm leading-6 text-aura-muted">
                <span className="font-black text-aura-text">Hint:</span>{" "}
                {card.hint}
              </p>

              <p className="mt-2 text-sm leading-6 text-aura-muted">
                {card.explanation}
              </p>
            </details>
          ))}
        </div>
      </div>
    );
  }

  if (toolName === "Tables" && isTablesResponse(result)) {
    return (
      <div>
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.22em] text-aura-cyan">
              Saved Table
            </p>

            <h3 className="mt-1 text-xl font-black text-aura-text">
              {result.table.title}
            </h3>

            <p className="mt-2 text-sm leading-6 text-aura-muted">
              {result.table.description}
            </p>
          </div>

          <ProviderBadge result={result} />
        </div>

        <div className="aura-scrollbar mt-5 overflow-x-auto rounded-2xl border border-aura-border">
          <table className="w-full min-w-[680px] border-collapse bg-aura-bg-soft text-left text-sm">
            <thead className="bg-aura-panel text-xs uppercase tracking-wider text-aura-dim">
              <tr>
                {result.table.columns.map((column) => (
                  <th
                    key={column.key}
                    className="border-b border-aura-border px-4 py-3"
                  >
                    {column.label}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {result.table.rows.map((row, rowIndex) => (
                <tr
                  key={rowIndex}
                  className="border-b border-aura-border/70 last:border-0"
                >
                  {result.table.columns.map((column, columnIndex) => (
                    <td
                      key={column.key}
                      className="px-4 py-3 leading-6 text-aura-muted"
                    >
                      {getRowValue(row as TableRow, column, columnIndex)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-4 grid gap-3 md:hidden">
          {result.table.rows.map((row, rowIndex) => (
            <div
              key={rowIndex}
              className="rounded-2xl border border-aura-border bg-aura-bg-soft p-4"
            >
              {result.table.columns.map((column, columnIndex) => (
                <div
                  key={column.key}
                  className="border-b border-aura-border/50 py-2 last:border-0"
                >
                  <p className="text-[10px] font-black uppercase tracking-wider text-aura-dim">
                    {column.label}
                  </p>
                  <p className="mt-1 text-sm leading-6 text-aura-muted">
                    {getRowValue(row as TableRow, column, columnIndex)}
                  </p>
                </div>
              ))}
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (toolName === "Mind Map" && isMindMapResponse(result)) {
    return (
      <div>
        <div className="flex justify-end">
          <ProviderBadge result={result} />
        </div>

        <div className="mt-3 rounded-[1.5rem] border border-aura-cyan/40 bg-aura-cyan/10 p-5 text-center">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-aura-cyan">
            Center Topic
          </p>

          <h3 className="mt-2 text-2xl font-black text-aura-text">
            {result.mindMap.center}
          </h3>

          <p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-aura-muted">
            {result.mindMap.description}
          </p>
        </div>

        <div className="mt-5 grid gap-4 md:grid-cols-2">
          {result.mindMap.branches.map((branch, index) => (
            <div
              key={`${branch.title}-${index}`}
              className="rounded-2xl border border-aura-border bg-aura-bg-soft p-4"
            >
              <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
                Branch {index + 1}
              </p>

              <h4 className="mt-2 text-lg font-black text-aura-text">
                {branch.title}
              </h4>

              <p className="mt-2 text-sm leading-6 text-aura-muted">
                {branch.summary}
              </p>

              <div className="mt-3 flex flex-wrap gap-2">
                {branch.keywords.map((keyword) => (
                  <span
                    key={keyword}
                    className="rounded-full border border-aura-border bg-aura-panel px-3 py-1 text-xs font-bold text-aura-muted"
                  >
                    {keyword}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (toolName === "Slides" && isSlidesResponse(result)) {
    return (
      <div className="space-y-4">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.22em] text-aura-cyan">
              Saved Slides
            </p>

            <h3 className="mt-1 text-xl font-black text-aura-text">
              {result.deck.title}
            </h3>

            <p className="mt-2 text-sm leading-6 text-aura-muted">
              {result.deck.description}
            </p>
          </div>

          <ProviderBadge result={result} />
        </div>

        {result.deck.slides.map((slide) => (
          <div
            key={slide.slideNumber}
            className="rounded-2xl border border-aura-border bg-aura-bg-soft p-5"
          >
            <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
              Slide {slide.slideNumber}
            </p>

            <h4 className="mt-2 text-xl font-black text-aura-text">
              {slide.title}
            </h4>

            <p className="mt-1 text-sm font-semibold text-aura-muted">
              {slide.subtitle}
            </p>

            <ul className="mt-4 space-y-2">
              {slide.bullets.map((bullet) => (
                <li key={bullet} className="text-sm leading-6 text-aura-muted">
                  • {bullet}
                </li>
              ))}
            </ul>

            <div className="mt-4 grid gap-3 md:grid-cols-2">
              <div className="rounded-xl border border-aura-border bg-aura-panel p-3">
                <p className="text-xs font-black uppercase tracking-wider text-aura-dim">
                  Speaker Notes
                </p>

                <p className="mt-2 text-sm leading-6 text-aura-muted">
                  {slide.speakerNotes}
                </p>
              </div>

              <div className="rounded-xl border border-aura-border bg-aura-panel p-3">
                <p className="text-xs font-black uppercase tracking-wider text-aura-dim">
                  Visual Idea
                </p>

                <p className="mt-2 text-sm leading-6 text-aura-muted">
                  {slide.visualIdea}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    );
  }

  if (toolName === "Audio" && isAudioResponse(result)) {
    return (
      <div className="space-y-4">
        <div className="rounded-[1.5rem] border border-aura-border bg-aura-bg-soft p-5">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="text-xs font-black uppercase tracking-[0.2em] text-aura-cyan">
                Audio Overview
              </p>

              <h3 className="mt-2 text-2xl font-black text-aura-text">
                {result.audioOverview.title}
              </h3>
            </div>

            <ProviderBadge result={result} />
          </div>

          <p className="mt-2 text-sm leading-6 text-aura-muted">
            {result.audioOverview.description}
          </p>

          <p className="mt-3 text-xs font-black uppercase tracking-wider text-aura-dim">
            Estimated Duration: {result.audioOverview.estimatedDuration}
          </p>
        </div>

        <div className="space-y-3">
          {result.audioOverview.segments.map((segment, index) => (
            <div
              key={`${segment.speaker}-${index}`}
              className="rounded-2xl border border-aura-border bg-aura-bg-soft p-4"
            >
              <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
                {segment.speaker}
              </p>

              <p className="mt-2 text-sm leading-6 text-aura-muted">
                {segment.text}
              </p>
            </div>
          ))}
        </div>

        <div className="rounded-2xl border border-aura-cyan/40 bg-aura-cyan/10 p-4">
          <p className="text-xs font-black uppercase tracking-wider text-aura-cyan">
            Recap
          </p>

          <ul className="mt-3 space-y-2">
            {result.audioOverview.recap.map((item) => (
              <li key={item} className="text-sm leading-6 text-aura-muted">
                • {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
    );
  }

  return <FallbackJsonView result={result} />;
};

export default AIToolResultRenderer;