const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');

function log(msg) {
  console.log(`\x1b[34m[SETUP]\x1b[0m ${msg}`);
}

function warn(msg) {
  console.log(`\x1b[33m[WARNING]\x1b[0m ${msg}`);
}

function error(msg) {
  console.error(`\x1b[31m[ERROR]\x1b[0m ${msg}`);
  process.exit(1);
}

log('Starting Study Aura Team Setup...');

// 1. Check for .env
const envPath = path.join(rootDir, '.env');
const envExamplePath = path.join(rootDir, '.env.example');

if (!fs.existsSync(envPath)) {
  log('Creating .env from .env.example...');
  fs.copyFileSync(envExamplePath, envPath);
  log('\x1b[33m[ACTION REQUIRED]\x1b[0m Please edit the .env file in the root folder.');
  log('Ask your lead for the shared team API keys or add your own.');
} else {
  log('.env file detected.');
}

// 2. Validate prerequisites
try {
  execSync('docker --version', { stdio: 'ignore' });
} catch (e) {
  error('Docker is not installed. Please install Docker Desktop.');
}

try {
  execSync('node --version', { stdio: 'ignore' });
} catch (e) {
  error('Node.js is not installed. Please install Node.js.');
}

// 3. Propagate Envs to Frontend
function syncEnv() {
  if (!fs.existsSync(envPath)) return;
  
  const rootEnvContent = fs.readFileSync(envPath, 'utf8');
  const frontendEnvPath = path.join(rootDir, 'frontend', '.env');

  // Filter for VITE_ prefixed variables or infra
  const frontendEnvs = rootEnvContent
    .split('\n')
    .filter(line => {
      const trimmed = line.trim();
      return trimmed.startsWith('VITE_') || 
             trimmed.startsWith('N8N_WEBHOOK_BASE_URL') || 
             trimmed.startsWith('YOUTUBE_HELPER_URL');
    })
    .join('\n');

  fs.writeFileSync(frontendEnvPath, `# GENERATED BY SETUP - DO NOT EDIT MANUALLY\n${frontendEnvs}`);
  log('Synced root environment variables to frontend.');
}

syncEnv();

// 4. Install dependencies
log('Checking for missing node_modules...');

const folders = [rootDir, path.join(rootDir, 'frontend')];
folders.forEach(folder => {
  if (!fs.existsSync(path.join(folder, 'node_modules'))) {
    log(`Installing dependencies in ${path.relative(rootDir, folder) || 'root'}...`);
    try {
      execSync('npm install', { cwd: folder, stdio: 'inherit' });
    } catch (e) {
      warn(`Installation in ${folder} had issues.`);
    }
  } else {
    log(`Dependencies already installed in ${path.relative(rootDir, folder) || 'root'}.`);
  }
});

log('\x1b[32m[SUCCESS]\x1b[0m Setup complete!');
log('To start the project:');
log('1. Ensure your .env has GEMINI_API_KEY and VITE_SUPABASE_URL.');
log('2. Run "npm run dev" or start.bat');
